python3 CoL_NetworkTraffic.py --seed 0
python3 CoL_NetworkTraffic.py --seed 1
python3 CoL_NetworkTraffic.py --seed 2
python3 CoL_NetworkTraffic.py --seed 3
python3 CoL_NetworkTraffic.py --seed 4
python3 CoL_NetworkTraffic.py --seed 5
python3 CoL_NetworkTraffic.py --seed 6
python3 CoL_NetworkTraffic.py --seed 7
python3 CoL_NetworkTraffic.py --seed 8
python3 CoL_NetworkTraffic.py --seed 9